config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, path: '', path_names: { sign_in: 'login', sign_out: 'logout',
      sign_up: 'register' }, controllers: { registrations: 'customers/registrations' }

  namespace :admin do

    devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
    root to: 'dashboard#index', as: 'dashboard'

    resources :customers do
      collection do
        get :search
      end
      member do
        delete :destroy_cover_image
      end
    end

    resources :equipaments do
      collection do
        get :search
      end
      member do
        delete :destroy_avatar_image
      end
    end

    resources :maintenances

    resources :orders do
      collection do
        get :put_fineshed_order
        get :put_canceled_order
        get :put_paid_order
      end
      member do
        get :cancel_order
        get :payment_order
        get :finished_order
        delete :destroy_category_image
      end
    end
  end

  get "sobre", to: "welcome#sobre"
  get "privacidade_termos", to: "welcome#privacidade_termos"
  get "list_equipament", to: "welcome#list_equipament"
  get 'welcome/details_equipament/:id', to: 'welcome#details_equipament', as: 'details_equipament'
  get 'welcome/rental_history', to: 'welcome#rental_history', as: 'my_rental_history'

  resources :rentals, only: [:new, :create, :show]

  resources :contacts, only: [:new, :create]

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/order.rb
class Order < ApplicationRecord
  attr_accessor :credit_card_name, :credit_card_number, :credit_card_expiry_month, :credit_card_expiry_year,
                :credit_card_security_code, :pix_amount, :boleto_amount, :boleto_code,
                :total_rent_value, :tot_rent_value_display

  belongs_to :customer
  belongs_to :equipament
  has_one :schedule

  enum status: { pending: "pending", inprogress: "inprogress", canceled: "canceled", finished: "finished" }

  before_validation :generate_code, on: :create

  after_create :generate_schedule

  validates :period_start, :period_end, :rent_value, :tot_rent_value, :payment_method, presence: true
  validates :tot_rent_value, numericality: { greater_than: 0 }
  validates :rent_value, numericality: { greater_than: 0 }
  validates :period_start, :period_end, comparison: { greater_than_or_equal_to: -> { Date.today + 1 } }
  validates :period_end, comparison: { greater_than_or_equal_to: :period_start }

  with_options if: -> { payment_method == "cartao" } do
    validates :credit_card_name, presence: { message: "não pode ficar em branco" }
    validates :credit_card_number, presence: { message: "não pode ficar em branco" }
    validates :credit_card_expiry_month, presence: { message: "não pode ficar em branco" }
    validates :credit_card_expiry_year, presence: { message: "não pode ficar em branco" }
    validates :credit_card_security_code, presence: { message: "não pode ficar em branco" }
  end

  def self.current_year_completed_summary
    result = find_by_sql(["
      SELECT COUNT(*) AS total_orders, SUM(tot_rent_value) AS total_value
      FROM orders
      WHERE extract(year from created_at) = ?
      AND status NOT IN ('pending','canceled')
    ", Date.current.year]).first

    OpenStruct.new(total_orders: result.total_orders, total_value: result.total_value)
  end

  scope :in_progress_and_expired, lambda { |order_code = nil|
    query = where(status: "inprogress").where("period_end < ?", Date.today)
    query = query.where("order_code LIKE ?", "%#{order_code}%") if order_code.present?
    query
  }

  scope :pending_and_expired, lambda { |order_code = nil|
    query = where(status: "pending").where("period_end < ?", Date.today)
    query = query.where("order_code LIKE ?", "%#{order_code}%") if order_code.present?
    query
  }

  scope :pending_not_expired, lambda { |order_code = nil|
    query = where(status: "pending").where("period_start > ?", Date.today)
    query = query.where("order_code LIKE ?", "%#{order_code}%") if order_code.present?
    query
  }

  private

  def generate_schedule
    schedule = build_schedule(
      equipament:,
      period_start:,
      period_end: period_end || Date.new(2099, 12, 31)
    )
    schedule.save!
  end

  def creating_via_create_action?
    new_record? && self.class.connection.transaction_open?
  end

  def generate_code
    datetime_part = DateTime.now.strftime("%Y%m%d%H%M%S%L")
    random_number = rand(0..9)
    self.order_code = "#{datetime_part}#{random_number}"
  end
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

module Admin
  class OrdersController < Admin::AdminController

    include Pagy::Backend

    before_action :load_order, only: %i[show edit update destroy cancel_order payment_order finished_order]

    def index
      if params[:search].present?
        @pagy, @orders = pagy(Order.where("order_code LIKE ?", "%#{params[:search]}%"), limit: 9)
      else
        @pagy, @orders = pagy(Order.order(created_at: :desc), limit: 9)
      end
    end

    def show; end

    def new
      @order = Order.new
      @min_date = Date.today + 1
    end

    def edit; end

    def create
      @order = Order.new(order_params)
      # authorize @order
      if @order.save
        equipament = Equipament.find(order_params[:equipament_id])
        equipament.unavailable!
        OrderMailer.send_order_receipt(@order.id).deliver_later
        redirect_to(admin_order_path(@order), notice: "Pedido cadastrado com sucesso !!!")
      else
        @min_date = Date.today + 1 ## .strftime("%d/%m/%Y")
        render(:new, status: :unprocessable_content)
      end
    end

    def update
      if @order.update(order_params)
        redirect_to(admin_order_path(@order), notice: "Pedido atualizado com sucesso !!!")
      else
        render(:edit, status: :unprocessable_content)
      end
    end

    def destroy
      @order.destroy!
    end

    def put_fineshed_order
      if params[:search].present?
        @pagy, @orders = pagy(Order.in_progress_and_expired(params[:search]), limit: 9)
      else
        @pagy, @orders = pagy(Order.in_progress_and_expired, limit: 9)
      end
    end

    def put_canceled_order
      if params[:search].present?
        @pagy, @orders = pagy(Order.pending_and_expired(params[:search]), limit: 9)
      else
        @pagy, @orders = pagy(Order.pending_and_expired, limit: 9)
      end
    end

    def put_paid_order
      if params[:search].present?
        @pagy, @orders = pagy(Order.pending_not_expired(params[:search]), limit: 9)
      else
        @pagy, @orders = pagy(Order.pending_not_expired, limit: 9)
      end
    end

    def cancel_order
      @order.update_column(:status, "canceled")
      equipament = Equipament.find(@order.equipament_id)
      equipament.available!
      schedule = Schedule.find_by(order_id: @order.id)
      schedule.done!
      OrderMailer.send_order_canceled(@order.id).deliver_later
      redirect_to put_canceled_order_admin_orders_path, notice: "Pedido #{@order.order_code} cancelado !!"
    end

    def payment_order
      @order.update_column(:status, "inprogress")
      OrderMailer.send_order_payment(@order.id).deliver_later
      redirect_to put_paid_order_admin_orders_path, notice: "Pedido #{@order.order_code} pagamento confirmado !!"
    end

    def finished_order
      @order.update_column(:status, "finished")
      equipament = Equipament.find(@order.equipament_id)
      equipament.available!
      schedule = Schedule.find_by(order_id: @order.id)
      schedule.done!
      OrderMailer.send_order_canceled(@order.id).deliver_later
      redirect_to put_fineshed_order_admin_orders_path, notice: "Pedido #{@order.order_code} finalizado !!"
    end

    private

    def load_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(
        :customer_id,
        :equipament_id,
        :order_code,
        :period_start,
        :period_end,
        :status,
        :rent_value,
        :tot_rent_value,
        :payment_method,
        :installments,
        :pix_code,
        :ticket_barcode
      )
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<section class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-8 mb-3">
      <div class="card mb-4">
        <div class="card-header bg-primary text-white text-center">
          <h4>Cadastro de Pedidos</h4>
        </div>
        <div class="card">
          <div class="card-body">
            <%= simple_form_for [:admin, @order] do |form| %>
              <div class="row">
                <div class="col-12 col-md-8">
                  <%= form.input :customer_id, required: true do  %>
                    <div data-controller="autocomplete" data-autocomplete-url-value="<%= search_admin_customers_path %>" role="combobox">
                      <input type="text" class="form-control" data-autocomplete-target="input" value="<%= form.object.customer&.name %>">
                      <%= form.input_field :customer_id, as: :hidden, data: { autocomplete_target: "hidden" } %>
                      <ul class="list-group" data-autocomplete-target="results"></ul>
                    
                    </div>
                  <% end %>
                  <%= form.full_error :customer, class: "mb-3" %>
                </div>
                <div class="row" data-controller="order-equipament" data-order-equipament-url-value="<%= search_admin_equipaments_path %>" role="combobox">
                  <div class="col-12 col-md-4">
                    <%= form.input :period_start, as: :date, html5: true, input_html: { min: @min_date,  data: { order_equipament_target: "periodStart"}} %>
                  </div>
                  <div class="col-12 col-md-4">
                    <%= form.input :period_end, html5: true, as: :date, input_html: { min: @min_date, data: { order_equipament_target: "periodEnd"}} %>
                  </div>
                  <div class="col-12 col-md-8">
                    <%= form.input :equipament_id, required: true do  %>
                      <div role="combobox">
                        <input type="text" class="form-control" data-order-equipament-target="input" value="<%= form.object.equipament&.name %>">
                        <%= form.input_field :equipament_id, as: :hidden, data: { order_equipament_target: "hidden" } %>
                        <ul class="list-group" data-order-equipament-target="results"></ul>
                      
                      </div>
                    <% end %>
                    <%= form.full_error :equipament %>
                  </div>
                  <div class="d-flex">
                    <div class="col-md-4 mb-3 me-4">
                      <%= form.input :rent_value_display, input_html: { class: 'form-control', readonly: true, value: format_currency(@order&.rent_value), data: { order_equipament_target: "rentValueDisplay" } } %>
                      <%= form.hidden_field :rent_value, "data-order-equipament-target": "rentValue" %>
                    </div>
                    <div class="col-md-4 mb-3">
                      <%= form.input :tot_rent_value_display, input_html: { class: 'form-control', readonly: true, value: format_currency(@order&.tot_rent_value), data: { order_equipament_target: "totalValueDisplay" }, id:"order_tot_rent_value"} %>
                      <%= form.hidden_field :tot_rent_value, "data-order-equipament-target": "totalValue" %>
                    </div>
                  </div>
                  <!-- Campos de Pagamento -->
                  <div data-order-equipament-target="paymentOptions" class="mt-3 d-none">
                    <h5>Opções de Pagamento</h5>
                    <div>
                    <div class="form-check">
                      <%= form.radio_button :payment_method, 'pix', class: 'form-check-input', data: { action: 'change->order-equipament#onPaymentMethodChange' } %>
                      <%= form.label :payment_method_pix, 'PIX', class: 'form-check-label' %>
                    </div>
                    <div class="form-check">
                      <%= form.radio_button :payment_method, 'boleto', class: 'form-check-input', data: { action: 'change->order-equipament#onPaymentMethodChange' } %>
                      <%= form.label :payment_method_boleto, 'Boleto', class: 'form-check-label' %>
                    </div>
                    </div>
                    <div id="pix-fields" class="d-none" data-order-equipament-target="pixFields">
                      <div class="row mb-3">
                        <div class="col-md-6">
                          <%= form.input :total_rent_value, as: :string, input_html: { class: 'form-control', readonly: true, "data-order-equipament-target": "pixTotalValue" } %>
                        </div>
                        <div class="col-md-6">
                          <%= form.input :pix_code, label: 'Código PIX', input_html: { class: 'form-control', readonly: true, value: '123456789012345' } %>
                        </div>
                      </div>
                    </div>
                    <div id="boleto-fields" class="d-none" data-order-equipament-target="boletoFields">
                      <div class="row mb-3">
                        <div class="col-md-5">
                          <%= form.input :total_rent_value, as: :string, input_html: { class: 'form-control', readonly: true, "data-order-equipament-target": "boletoTotalValue" } %>
                        </div>
                        <div class="col-md-7">
                          <%= form.input :ticket_barcode, label: 'Código de Barras do Boleto', input_html: { class: 'form-control', readonly: true, value: '12345678901234567890123456789012345678901234' } %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer d-flex justify-content-between">
                <%= link_to "Voltar", admin_orders_path, class: "btn btn-secondary"%>
                <%= form.button :button, class:"btn btn-primary" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/admin/orders/_order.html.erb
<div class="container" id="<%= dom_id order %>">
  <% flash.each do |key, value| %>
    <div data-controller="flash-message" data-action="click->flash-message#removeMessage" id="flash-message" class="flash <%= key %> alert alert-success bold text-black" data-flash-message-target="message"><%= value %></div>
  <% end %>
  <div class="mb-4 card card-primary mx-auto" style="max-width: 800px;">
    <div class="card-header bg-primary text-white text-center">
      <h4>Detalhes do Pedido</h4>
    </div>
    <div class="card-body">
      <div class="mb-2">
        <span class="flex-grow-1 fw-bold">Codigo Pedido: </span>
        <span class="mx-3"> <%= order&.order_code %> </span>
      </div>
      <div class="mb-2">
        <span class="flex-grow-1 fw-bold">Cliente: </span>
        <span class="mx-3"> <%= order.customer.name %> </span>
      </div>
      <div class="mb-2">
        <span class="flex-grow-1 fw-bold">Equipamento: </span>
        <span class="mx-3"> <%= order.equipament.name %> </span>
      </div>
      <div class="mb-2">
        <span class="flex-grow-1 fw-bold">Data Início: </span>
        <span class="mx-3"> <%= order&.period_start.strftime('%d/%m/%Y') %> </span>
      </div>
      <div class="mb-2">
        <span class="flex-grow-1 fw-bold">Data Fim: </span>
        <span class="mx-3"> <%= order&.period_end.strftime('%d/%m/%Y') %> </span>
      </div>
      <div class="mb-2">
        <span class="flex-grow-1 fw-bold">Status: </span>
        <span class="mx-3"> <%= order&.status %> </span>
      </div>
      <div class="mb-2">
        <span class="flex-grow-1 fw-bold">Valor Aluguel: </span>
        <span class="mx-3"> <%= number_to_currency(order.tot_rent_value, unit: "R$ ", separator: ",", delimiter: ".") %> </span>
      </div>
      <h5>Detalhes do Pagamento</h5>
      <div class="row mb-3">
        <div class="col-md-6">
          <p><strong>Método de Pagamento:</strong> <%= order&.payment_method.capitalize %></p>
        </div>
        <div class="col-md-6">
          <p><strong>Valor a pagar:</strong> <%= number_to_currency(order&.tot_rent_value, unit: "R$ ", separator: ",", delimiter: ".") %></p>
        </div>
        <% if order.payment_method == 'pix' %>
          <div class="row mb-3">
            <div class="col-md-6">
              <p><strong>Código PIX:</strong> <%= order&.pix_code %></p>
            </div>
          </div>
        <% elsif order.payment_method == 'boleto' %>
          <div class="row mb-3">
            <div class="col-md-6">
              <p><strong>Código de Barras do Boleto:</strong> <%= order&.ticket_barcode %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="card-footer">
      <a href="<%= edit_admin_order_path(order) %>" class="btn btn-primary">Editar</a>
      <a href="<%= admin_orders_path %>" class="btn btn-secondary">Ver Lista</a>
    </div>
  </div>
</div>

app/views/admin/orders/_toolbar.html.erb
<div class="toolbar py-5 pb-lg-15" id="kt_toolbar" >
  <div id="kt_toolbar_container" class="container-xxl d-flex flex-wrap flex-stack" >
    <div class="page-title d-flex flex-column me-3" >
      <h1 class="d-flex text-black fw-bold my-1 ">Pedidos</h1>
    </div>
    <div class="d-flex align-items-center py-3 py-md-1" >
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container-fluid mb-3">
  <div class="d-flex align-items-center mb-2">
    <h3 class="flex-grow-1">Lista de Pedidos</h3>
    <div class="input-group ms-3" style="width: 550px;">
      <%= form_with url: admin_orders_path, method: :get, local: true, class: "d-flex w-100" do %>
        <%= text_field_tag :search, nil, class: "form-control input-sm", placeholder: "Pesquisar Pedido(s)...", aria_label: "Pesquisar" %>
        <%= button_tag(type: 'submit', class: "btn btn-success me-3", title: "Pesquisar") do %>
          <%= image_tag "icons/gray/lupa.svg" %>
        <% end %>
      <% end %>
    </div>
    <div class="list-actions">
      <%= link_to "Novo", new_admin_order_path, class: "ms-3 btn btn-primary" %>
    </div>
  </div>
  <div class="row">
    <% if @pagy.count > 9 %>
      <div class="col-md-12 d-flex justify-content-center">
        <%= pagy_bootstrap_nav(@pagy).html_safe%>
      </div>
    <% end %>
  </div>
  <section>
    <div class="row">
      <div class="col">
        <table class="table table-bordered table-striped">
          <thead class="thead-dark">
            <tr>
              <th class="bg-black text-white" scope="col">Código Pedido</th>
              <th class="bg-black text-white" scope="col">Cliente</th>
              <th class="bg-black text-white" scope="col">Equipamento</th>
              <th class="bg-black text-white" scope="col">Início</th>
              <th class="bg-black text-white" scope="col">Fim</th>
              <th class="bg-black text-white" scope="col">R$ Aluguel</th>
              <th class="bg-black text-white" scope="col">Status</th>
              <th class="bg-black text-white" scope="col">Ações</th>
            </tr>
          </thead>
          <tbody>
            <!-- Exemplo de pedidos cadastrados -->
            <% @orders.each do |order| %>
              <tr>
                <td><%= order&.order_code %></td>
                <td><%= order.customer.name %></td>
                <td><%= order.equipament.name %></td>
                <td><%= order&.period_start.strftime('%d/%m/%Y') %></td>
                <td><%= order&.period_end.strftime('%d/%m/%Y') %></td>
                <td><%= number_to_currency(order.tot_rent_value, unit: "R$ ", separator: ",", delimiter: ".") %></td>
                <td><%= order.status %></td>
                <td class="d-flex justify-content-between">
                  <% if order.status == "pending" %>
                    <%= link_to edit_admin_order_path(order), class: "text-black-500 hover:underline", title: "Edit", alt: "edit"  do %>
                      <%= image_tag "icons/gray/edit.svg" %>
                    <% end %>
                    <%= link_to admin_order_path(order), method: :delete, data: {
                          turbo_method: :delete, turbo_confirm: 'Are you sure?' }, 
                          class: "text-red-500 hover:underline", title: "Delete", alt: "delete"   do  %>
                      <%= image_tag "icons/gray/close.svg" %>
                    <% end %>
                  <% end %>
                </td>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/orders/put_canceled_order.html.erb
<div class="container-fluid">
  <% flash.each do |key, value| %>
    <div data-controller="flash-message" data-action="click->flash-message#removeMessage" id="flash-message" class="flash <%= key %> alert alert-success bold text-black" data-flash-message-target="message"><%= value %></div>
  <% end %>
  <div class="d-flex align-items-center mb-2">
    <h3 class="flex-grow-1">Lista de Pedidos com pagamento pendente</h3>
    <div class="input-group ms-3" style="width: 550px;">
      <%= form_with url: put_canceled_order_admin_orders_path, method: :get, local: true, class: "d-flex w-100" do %>
        <%= text_field_tag :search, nil, class: "form-control input-sm", placeholder: "Pesquisar Pedido(s)...", aria_label: "Pesquisar" %>
        <%= button_tag(type: 'submit', class: "btn btn-success me-3", title: "Pesquisar") do %>
          <%= image_tag "icons/gray/lupa.svg" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <% if @pagy.count > 9 %>
      <div class="col-md-12 d-flex justify-content-center">
        <%= pagy_bootstrap_nav(@pagy).html_safe%>
      </div>
    <% end %>
  </div>
  <section>
    <div class="row">
      <div class="col">
        <table class="table table-bordered table-striped">
          <thead class="thead-dark">
            <tr>
              <th class="bg-black text-white" scope="col">Código Pedido</th>
              <th class="bg-black text-white" scope="col">Cliente</th>
              <th class="bg-black text-white" scope="col">Equipamento</th>
              <th class="bg-black text-white" scope="col">Início</th>
              <th class="bg-black text-white" scope="col">Fim</th>
              <th class="bg-black text-white" scope="col">R$ Aluguel</th>
              <th class="bg-black text-white" scope="col">Status</th>
              <th class="bg-black text-white" scope="col">Ações</th>
            </tr>
          </thead>
          <tbody>
            <!-- Exemplo de pedidos cadastrados -->
            <% @orders.each do |order| %>
              <tr>
                <td><%= order&.order_code %></td>
                <td><%= order.customer.name %></td>
                <td><%= order.equipament.name %></td>
                <td><%= order&.period_start.strftime('%d/%m/%Y') %></td>
                <td><%= order&.period_end.strftime('%d/%m/%Y') %></td>
                <td><%= number_to_currency(order.tot_rent_value, unit: "R$ ", separator: ",", delimiter: ".") %></td>
                <td><%= order.status %></td>
                <td class="d-flex justify-content-between">
                  <%= link_to cancel_order_admin_order_path(order), class: "text-black-500 hover:underline", title: "Cancelar", alt: "cancel"  do %>
                    <%= image_tag "icons/gray/close.svg" %>
                  <% end %>
                </td>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/orders/put_fineshed_order.html.erb
<div class="container-fluid">
  <% flash.each do |key, value| %>
    <div data-controller="flash-message" data-action="click->flash-message#removeMessage" id="flash-message" class="flash <%= key %> alert alert-success bold text-black" data-flash-message-target="message"><%= value %></div>
  <% end %>
  <div class="d-flex align-items-center mb-2">
    <h3 class="flex-grow-1">Lista de Pedidos para Finalizar</h3>
    <div class="input-group ms-3" style="width: 550px;">
      <%= form_with url: put_fineshed_order_admin_orders_path, method: :get, local: true, class: "d-flex w-100" do %>
        <%= text_field_tag :search, nil, class: "form-control input-sm", placeholder: "Pesquisar Pedido(s)...", aria_label: "Pesquisar" %>
        <%= button_tag(type: 'submit', class: "btn btn-success me-3", title: "Pesquisar") do %>
          <%= image_tag "icons/gray/lupa.svg" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <% if @pagy.count > 9 %>
      <div class="col-md-12 d-flex justify-content-center">
        <%= pagy_bootstrap_nav(@pagy).html_safe%>
      </div>
    <% end %>
  </div>
  <section>
    <div class="row">
      <div class="col">
        <table class="table table-bordered table-striped">
          <thead class="thead-dark">
            <tr>
              <th class="bg-black text-white" scope="col">Código Pedido</th>
              <th class="bg-black text-white" scope="col">Cliente</th>
              <th class="bg-black text-white" scope="col">Equipamento</th>
              <th class="bg-black text-white" scope="col">Início</th>
              <th class="bg-black text-white" scope="col">Fim</th>
              <th class="bg-black text-white" scope="col">R$ Aluguel</th>
              <th class="bg-black text-white" scope="col">Status</th>
              <th class="bg-black text-white" scope="col">Ações</th>
            </tr>
          </thead>
          <tbody>
            <!-- Exemplo de pedidos cadastrados -->
            <% @orders.each do |order| %>
              <tr>
                <td><%= order&.order_code %></td>
                <td><%= order.customer.name %></td>
                <td><%= order.equipament.name %></td>
                <td><%= order&.period_start.strftime('%d/%m/%Y') %></td>
                <td><%= order&.period_end.strftime('%d/%m/%Y') %></td>
                <td><%= number_to_currency(order.tot_rent_value, unit: "R$ ", separator: ",", delimiter: ".") %></td>
                <td><%= order.status %></td>
                <td class="d-flex justify-content-between">
                  <%= link_to finished_order_admin_order_path(order), class: "text-black-500 hover:underline", title: "Finished", alt: "finished"  do %>
                    <%= image_tag "icons/gray/edit.svg" %>
                  <% end %>
                </td>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/orders/put_paid_order.html.erb
<div class="container-fluid">
  <% flash.each do |key, value| %>
    <div data-controller="flash-message" data-action="click->flash-message#removeMessage" id="flash-message" class="flash <%= key %> alert alert-success bold text-black" data-flash-message-target="message"><%= value %></div>
  <% end %>
  <div class="d-flex align-items-center mb-2">
    <h3 class="flex-grow-1">Lista de Pedidos, confirmar pagamento</h3>
    <div class="input-group ms-3" style="width: 550px;">
      <%= form_with url: put_paid_order_admin_orders_path, method: :get, local: true, class: "d-flex w-100" do %>
        <%= text_field_tag :search, nil, class: "form-control input-sm", placeholder: "Pesquisar Pedido(s)...", aria_label: "Pesquisar" %>
        <%= button_tag(type: 'submit', class: "btn btn-success me-3", title: "Pesquisar") do %>
          <%= image_tag "icons/gray/lupa.svg" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <% if @pagy.count > 9 %>
      <div class="col-md-12 d-flex justify-content-center">
        <%= pagy_bootstrap_nav(@pagy).html_safe%>
      </div>
    <% end %>
  </div>
  <section>
    <div class="row">
      <div class="col">
        <table class="table table-bordered table-striped">
          <thead class="thead-dark">
            <tr>
              <th class="bg-black text-white" scope="col">Código Pedido</th>
              <th class="bg-black text-white" scope="col">Cliente</th>
              <th class="bg-black text-white" scope="col">Equipamento</th>
              <th class="bg-black text-white" scope="col">Início</th>
              <th class="bg-black text-white" scope="col">Fim</th>
              <th class="bg-black text-white" scope="col">R$ Aluguel</th>
              <th class="bg-black text-white" scope="col">Status</th>
              <th class="bg-black text-white" scope="col">Ações</th>
            </tr>
          </thead>
          <tbody>
            <!-- Exemplo de pedidos cadastrados -->
            <% @orders.each do |order| %>
              <tr>
                <td><%= order&.order_code %></td>
                <td><%= order.customer.name %></td>
                <td><%= order.equipament.name %></td>
                <td><%= order&.period_start.strftime('%d/%m/%Y') %></td>
                <td><%= order&.period_end.strftime('%d/%m/%Y') %></td>
                <td><%= number_to_currency(order.tot_rent_value, unit: "R$ ", separator: ",", delimiter: ".") %></td>
                <td><%= order.status %></td>
                <td class="d-flex justify-content-between">
                  <%= link_to payment_order_admin_order_path(order), class: "text-black-500 hover:underline", title: "Confirmar Pagamento", alt: "pagamento"  do %>
                    <%= image_tag "icons/gray/payment.svg" %>
                  <% end %>
                </td>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/orders/show.html.erb
<%= render @order %>