config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, path: '', path_names: { sign_in: 'login', sign_out: 'logout',
      sign_up: 'register' }, controllers: { registrations: 'customers/registrations' }

  namespace :admin do

    devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
    root to: 'dashboard#index', as: 'dashboard'

    resources :customers do
      collection do
        get :search
      end
      member do
        delete :destroy_cover_image
      end
    end

    resources :equipaments do
      collection do
        get :search
      end
      member do
        delete :destroy_avatar_image
      end
    end

    resources :maintenances

    resources :orders do
      collection do
        get :put_fineshed_order
        get :put_canceled_order
        get :put_paid_order
      end
      member do
        get :cancel_order
        get :payment_order
        get :finished_order
        delete :destroy_category_image
      end
    end
  end

  get "sobre", to: "welcome#sobre"
  get "privacidade_termos", to: "welcome#privacidade_termos"
  get "list_equipament", to: "welcome#list_equipament"
  get 'welcome/details_equipament/:id', to: 'welcome#details_equipament', as: 'details_equipament'
  get 'welcome/rental_history', to: 'welcome#rental_history', as: 'my_rental_history'

  resources :rentals, only: [:new, :create, :show]

  resources :contacts, only: [:new, :create]

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
end

app/views/shared/_footer.html.erb
<footer class="bg-dark text-white text-center p-3 fixed-bottom">
  <div class="container">
    <div class="d-flex flex-column flex-md-row justify-content-center align-items-center mb-3">
      <p class="mb-0 me-md-4">&copy; <%= Time.now.year %> EquipoRent. Todos os direitos reservados.</p>
      <div class="social-icons mt-3 mt-md-0">
        <a class="me-3" href="#"><%= image_tag "icons/gray/facebook.svg", alt: "Facebook" %></a>
        <a class="me-3" href="#"><%= image_tag "icons/gray/twitter.svg", alt: "Twitter" %></a>
        <a class="me-3" href="#"><%= image_tag "icons/gray/instagram.svg", alt: "Instagram" %></a>
        <a class="me-3" href="#"><%= image_tag "icons/gray/linkedin.svg", alt: "LinkedIn" %></a>
      </div>
    </div>
    <div>
      <%= link_to 'Política de Privacidade', privacidade_termos_path, class: 'text-white mx-2' %>
      <%= link_to 'Termos de Uso', privacidade_termos_path, class: 'text-white mx-2' %>
    </div>
  </div>
</footer>

app/views/shared/_footer_admin.html.erb
<footer class="bg-dark text-white text-center p-3 fixed-bottom">
  <div class="container">
    <div class="row mt-3">
      <div class="col">
        <p>&copy; 2024 EquipoRent. Todos os direitos reservados.</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-dark text-white p-2 fixed-top">
  <div class="container-fluid d-flex justify-content-between align-items-center">
    <div class="d-flex align-items-center">
      <%= image_tag('svg/engrenagem.svg', class: 'img-fluid', alt: 'logo equiporent', style: "width: 70%; height: auto;") %>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item me-5"><%= link_to 'Home', root_path, class: "nav-link text-white" %></li>
          <% if customer_signed_in? %>
            <li class="nav-item me-5"><%= link_to 'Alugueis', my_rental_history_path, class: "nav-link text-white" %></li>
          <% end %>
          <li class="nav-item me-5"><%= link_to 'Sobre', sobre_path, class: 'nav-link text-white' %></li>
          <li class="nav-item me-5"><%= link_to 'Contato', new_contact_path, class: 'nav-link text-white' %></li>
        </ul>
        <% if customer_signed_in? %>
          <div class="d-flex align-items-center ms-lg-3">
            <span class="text-white me-3"><%= current_customer.email %></span>
            <%= link_to destroy_customer_session_path, data: { "turbo-method": :delete }, class: "btn btn-danger" do %>
              Logout
            <% end %>
          </div>
        <% else %>
          <%= link_to 'Log in', new_customer_session_path, class: "btn btn-outline-light ms-lg-3" %>
        <% end %>
      </div>
    </nav>
  </div>
</header>

app/views/shared/_header_admin.html.erb
<header class="bg-dark text-white p-3 fixed-top">
  <div class="container-fluid d-flex justify-content-between align-items-center">
    <div class="d-flex align-items-center">
      <%= image_tag('svg/engrenagem.svg', alt: 'logo equiporent', style: "width: 70%; height: auto;") %>
    </div>
    <nav class="d-flex align-items-center">
      <ul class="nav">
        <li class="nav-item"><%= link_to 'Home', admin_dashboard_path, class: "nav-link text-white" %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="equipamentosDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
            Equipamentos
          </a>
          <ul class="dropdown-menu" aria-labelledby="equipamentosDropdown">
            <li><%= link_to 'Cadastro', admin_equipaments_path, class: "dropdown-item" %></li>
            <li><%= link_to 'Manutenção', admin_maintenances_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="clientesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
            Clientes
          </a>
          <ul class="dropdown-menu" aria-labelledby="clientesDropdown">
            <li><%= link_to 'Todos Clientes', admin_customers_path, class: "dropdown-item" %></li>
            <li><%= link_to 'Adicionar Cliente', new_admin_customer_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="pedidosDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
            Pedidos
          </a>
          <ul class="dropdown-menu" aria-labelledby="pedidosDropdown">
            <li><%= link_to 'Todos Pedidos', admin_orders_path, class: "dropdown-item"  %></li>
            <li><%= link_to 'Adicionar Pedido', new_admin_order_path, class: "dropdown-item"  %></li>
            <li><%= link_to 'Finalizar', put_fineshed_order_admin_orders_path, class: "dropdown-item"  %></li>
            <li><%= link_to 'Cancelar', put_canceled_order_admin_orders_path, class: "dropdown-item" %></li>
            <li><%= link_to 'Pagamento', put_paid_order_admin_orders_path, class: "dropdown-item"  %></li>
          </ul>
        </li>
      </ul>
    </nav>
    <% if admin_user_signed_in? %>
      <div data-turbo="true">
        <%= link_to destroy_admin_user_session_path, data: { "turbo-method": :delete }, class: "btn btn-danger" do %>
          Logout
        <% end %>
      </div>
    <% else %>
      <%= link_to 'Log in', new_admin_user_session_path, class: "btn btn-outline-light" %>
    <% end %>
  </div>
</header>