config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, path: '', path_names: { sign_in: 'login', sign_out: 'logout',
      sign_up: 'register' }, controllers: { registrations: 'customers/registrations' }

  namespace :admin do

    devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
    root to: 'dashboard#index', as: 'dashboard'

    resources :customers do
      collection do
        get :search
      end
      member do
        delete :destroy_cover_image
      end
    end

    resources :equipaments do
      collection do
        get :search
      end
      member do
        delete :destroy_avatar_image
      end
    end

    resources :maintenances

    resources :orders do
      collection do
        get :put_fineshed_order
        get :put_canceled_order
        get :put_paid_order
      end
      member do
        get :cancel_order
        get :payment_order
        get :finished_order
        delete :destroy_category_image
      end
    end
  end

  get "sobre", to: "welcome#sobre"
  get "privacidade_termos", to: "welcome#privacidade_termos"
  get "list_equipament", to: "welcome#list_equipament"
  get 'welcome/details_equipament/:id', to: 'welcome#details_equipament', as: 'details_equipament'
  get 'welcome/rental_history', to: 'welcome#rental_history', as: 'my_rental_history'

  resources :rentals, only: [:new, :create, :show]

  resources :contacts, only: [:new, :create]

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController

  include Pagy::Backend

  before_action :authenticate_customer!, only: %i[ rental_history ]

  def index
    @equipaments = Equipament.where(status: 'available').order('RANDOM()').limit(3)
  end

  def sobre; end

  def privacidade_termos; end

  def contato; end

  def list_equipament
    if params[:search].present?
      @pagy, @equipaments = pagy(Equipament.where('LOWER(name) LIKE ?', "%#{params[:search].downcase}%")
                               .where(status: ['available', 'unavailable'])
                               .order(:status), limit: 8)
    else
      @pagy, @equipaments = pagy(Equipament.where(status: ['available', 'unavailable']).order(:status), limit: 9)
    end
  end

  def details_equipament
    @equipament = Equipament.find(params[:id])
  end

  def rental_history
    @pagy, @order_history = pagy(current_customer.orders.order(created_at: :desc), limit: 4)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/details_equipament.html.erb
<!-- Seção de Informações -->
<section class="container py-5">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Detalhes do Equipamento</h4>
          <h5 class="card-subtitle mb-3"><%= @equipament.name %></h5>
          <div class="mb-2">
            <span class="flex-grow-1 fw-bold ml-4">Descrição: </span>
            <span class="mx-3"><%= raw @equipament.description.to_s %></span>
          </div>
          <div class="mb-2">
            <span class="fw-bold">Diária: </span>
            <span class="mx-3"><%= number_to_currency(@equipament.rent_value, unit: "R$ ", separator: ",", delimiter: ".") %></span>
          </div>
        </div>
        <div class="card-footer d-flex justify-content-between align-items-center">
          <p class="card-text mb-0 fw-bold ml-4">Status: <%= @equipament.status %></p>
          <% if @equipament.status == "available" %>
            <a href="<%= new_rental_path(id: @equipament.id) %>" class="btn btn-primary"><i class="fas fa-shopping-cart me-2"></i> Alugar</a>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="text-center">
        <%= image_tag @equipament.image.variant(:medium), 
              class: "img-fluid",  alt: "Imagem do Equipamento" 
               %>
      </div>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<!-- Seção de Apresentação -->
<div class="jumbotron text-center  bg-primary text-white">
  <div class="container">
    <h1 class="display-4">Alugue Equipamentos com Facilidade e Rapidez</h1>
    <p class="lead">Os melhores equipamentos ao seu alcance.</p>
    <%= link_to "Explore Equipamentos", list_equipament_path, class: "btn btn-light btn-lg mb-5", role: "button" %>
  </div>
</div>
<!-- Seção de Funcionalidades -->
<section class="container-fluid py-2">
  <div class="row text-center">
    <div class="col-md-3 mb-2">
      <i class="bi bi-box-seam fs-1 text-primary"></i>
      <h3>Aluguel Fácil</h3>
      <p>Encontre e alugue os melhores equipamentos de forma rápida e prática.</p>
    </div>
    <div class="col-md-3 mb-2">
      <i class="bi bi-journal-text fs-1 text-primary"></i>
      <h3>Gestão de Pedidos</h3>
      <p>Gerencie seus pedidos e acompanhe o status em tempo real.</p>
    </div>
    <div class="col-md-3 mb-2">
      <i class="bi bi-people fs-1 text-primary"></i>
      <h3>Cadastro de Clientes</h3>
      <p> <% if customer_signed_in? %>
            Cadastre seus dados e aproveite todas as vantagens.
          <% else %>
            <%= link_to "Cadastre seus dados e aproveite todas as vantagens.", new_customer_registration_path %> 
          <% end %> 
      </p>
    </div>
    <div class="col-md-3 mb-2">
      <i class="bi bi-tools fs-1 text-primary"></i>
      <h3>Equipamentos de Qualidade</h3>
      <p>Nossos equipamentos são de alta qualidade e bem conservados.</p>
    </div>
  </div>
</section>
<!-- Como Funciona -->
<section class="container-fluid  bg-light">
  <h2 class="text-center mb-4">Como Funciona</h2>
  <div class="row">
    <div class="col-md-3 text-center mb-4">
      <i class="bi bi-search fs-1 text-primary"></i>
      <h4>Pesquisar</h4>
      <p>Navegue pelos equipamentos disponíveis.</p>
    </div>
    <div class="col-md-3 text-center mb-4">
      <i class="bi bi-box-seam fs-1 text-primary"></i>
      <h4>Escolher</h4>
      <p>Selecione o equipamento que atende às suas necessidades.</p>
    </div>
    <div class="col-md-3 text-center mb-4">
      <i class="bi bi-calendar-check fs-1 text-primary"></i>
      <h4>Reservar</h4>
      <p>Escolha as datas e faça a reserva online.</p>
    </div>
    <div class="col-md-3 text-center mb-4">
      <i class="bi bi-tools fs-1 text-primary"></i>
      <h4>Usar</h4>
      <p>Receba o equipamento e utilize conforme necessário.</p>
    </div>
  </div>
</section>
<!-- Seção de Equipamentos Populares -->
<section class="bg-light ">
  <div class="container">
    <h2 class="mb-4 text-center">Equipamentos Populares</h2>
    <div class="row">
      <% @equipaments.each do |equipament| %>
        <div class="col-md-4 mb-4">
          <div class="card h-100">
            <div class="d-flex justify-content-center">
              <%= image_tag(equipament.image.variant(:thumb), class: "img-fluid img-thumbnail", style: "max-width: 250px; height: auto;", alt: "Imagem do Equipamento") %>
            </div>
            <div class="card-body d-flex flex-column justify-content-between">
              <h5 class="card-title text-center"><%= link_to equipament.name, details_equipament_path(equipament), class: "text-decoration-none text-primary" %></h5>
              <p class="card-text text-center">Diária: <%= number_to_currency(equipament.rent_value, unit: "R$ ", separator: ",", delimiter: ".") %></p>
              <div class="d-flex justify-content-between align-items-center">
                <p class="card-text mb-0">Status: <%= equipament.status %></p>
                <a href="<%= new_rental_path(id: equipament.id) %>" class="btn btn-primary"><i class="fas fa-shopping-cart me-2"></i> Alugar</a>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
<!-- Seção de Depoimentos de Clientes -->
<section class="container py-5">
  <h2 class="text-center mb-4">Depoimentos de Clientes</h2>
  <div class="row">
    <div class="col-md-6 mb-4">
      <blockquote class="blockquote d-flex flex-column align-items-start">
        <div class="d-flex align-items-center mb-2">
          <%= image_tag('svg/man-5.svg', alt:"Avatar de João Silva", class:"rounded-circle me-3", width:"50", height:"50") %>
          <span class="text-center" >João Silva</span>
        </div>
        <p class="mb-0">Serviço excelente, equipamentos de alta qualidade!</p>
      </blockquote>
    </div>
    <div class="col-md-6 mb-4">
      <blockquote class="blockquote d-flex flex-column align-items-start">
        <div class="d-flex align-items-center mb-2">
          <%= image_tag('svg/woman-1.svg', alt:"Avatar de Maria Oliveira", class:"rounded-circle me-3", width:"50", height:"50") %>
          <span class=" text-center" >Maria Oliveira</span>
        </div>
        <p class="mb-0">Fácil de usar e suporte rápido. Recomendo!</p>
      </blockquote>
    </div>
  </div>
</section>

app/views/welcome/list_equipament.html.erb
<!-- Seção de Pesquisa -->
<section class="container mt-3 mb-5">
  <div class="row mb-4">
    <div class="col-md-8 mx-auto">
      <h3 class="text-center mb-3">Lista de Equipamentos</h3>
      <div class="d-flex justify-content-between align-items-center">
        <div class="input-group me-5 mb-3">
          <%= form_with url: list_equipament_path, method: :get, local: true, class: "d-flex w-100" do %>
            <%= text_field_tag :search, nil, class: "form-control", placeholder: "Pesquisar Equipamento(s)...", aria_label: "Pesquisar" %>
            <%= button_tag(type: 'submit', class: "btn btn-success ms-3", title: "Pesquisar", alt: "pesquisar") do %>
              <%= image_tag "icons/gray/lupa.svg" %>
            <% end %>
          <% end %>
        </div>
        <% if @pagy.count > 0 %>
          <div class="ms-4">
            <%= pagy_bootstrap_nav(@pagy).html_safe %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <!-- Lista de Equipamentos -->
  <div class="row">
    <% @equipaments.each do |equipament| %>
      <div class="col-md-4 mb-4">
        <div class="d-flex align-items-center">
          <%= image_tag(equipament.image.variant(:thumb), class: "img-fluid img-thumbnail me-3", style: "max-width: 200px; height: auto;", alt: "Imagem do Equipamento") %>
          <div>
            <h5 class="card-title"><%= link_to equipament.name, details_equipament_path(equipament) %></h5>
            <p class="card-text">Diária: <%= number_to_currency(equipament.rent_value, unit: "R$ ", separator: ",", delimiter: ".") %></p>
            <p class="card-text">Status: <%= equipament.status %></p>
            <% if equipament.status == "available" %>
              <a href="<%= new_rental_path(id: equipament.id) %>" class="btn btn-primary"><i class="fas fa-shopping-cart me-2"></i> Alugar</a>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <!-- Paginação -->
  <div class="row">
    <div class="col-md-12 d-flex justify-content-center">
      <%= pagy_bootstrap_nav(@pagy).html_safe%>
    </div>
  </div>
</section>

app/views/welcome/privacidade_termos.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
      <h2 class="page-header">Política de Privacidade</h2>
      <p>Na [Nome da Sua Empresa], respeitamos a sua privacidade e estamos comprometidos em proteger suas informações pessoais. Esta Política de Privacidade explica como coletamos, usamos e protegemos os dados pessoais que você fornece ao utilizar nosso site.</p>
      <h3>Informações que Coletamos</h3>
      <p>Ao usar nosso site, podemos coletar certas informações pessoais, como nome, endereço de e-mail, número de telefone e outras informações que você nos fornece voluntariamente através de formulários de contato ou ao se cadastrar em nossa newsletter.</p>
      <h3>Como Usamos Suas Informações</h3>
      <p>As informações pessoais que coletamos são usadas para fornecer os serviços solicitados, processar transações, enviar comunicações de marketing, melhorar nosso site e atender às suas necessidades de forma mais eficaz.</p>
      <h3>Divulgação a Terceiros</h3>
      <p>Não vendemos, trocamos ou transferimos suas informações pessoais para terceiros sem seu consentimento, exceto quando exigido por lei ou para cumprir com os objetivos estabelecidos nesta Política de Privacidade.</p>
      <h3>Segurança das Informações</h3>
      <p>Implementamos medidas de segurança para proteger suas informações pessoais contra acesso não autorizado, alteração, divulgação ou destruição.</p>
      <h3>Alterações na Política de Privacidade</h3>
      <p>Reservamo-nos o direito de atualizar ou modificar esta Política de Privacidade a qualquer momento, e essas alterações serão publicadas nesta página.</p>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-md-12">
      <h2 class="page-header">Termos de Uso</h2>
      <h3>Uso do Site</h3>
      <p>Você concorda em usar nosso site apenas para fins legais e de acordo com estes Termos de Uso.</p>
      <h3>Propriedade Intelectual</h3>
      <p>Todo o conteúdo do site, incluindo textos, imagens, logotipos, e outros materiais, são propriedade da [Nome da Sua Empresa] e estão protegidos por leis de direitos autorais e outras leis de propriedade intelectual.</p>
      <h3>Links para Terceiros</h3>
      <p>Nosso site pode conter links para sites de terceiros que não estão sob nosso controle. Não nos responsabilizamos pelo conteúdo ou práticas de privacidade desses sites.</p>
      <h3>Limitação de Responsabilidade</h3>
      <p>Em nenhuma circunstância a [Nome da Sua Empresa] será responsável por danos diretos, indiretos, consequenciais, incidentais ou especiais decorrentes do uso ou incapacidade de usar nosso site.</p>
      <h3>Alterações nos Termos de Uso</h3>
      <p>Reservamo-nos o direito de atualizar ou modificar estes Termos de Uso a qualquer momento, e essas alterações serão efetivas imediatamente após serem publicadas nesta página.</p>
      <p>Ao continuar a utilizar nosso site, você concorda em cumprir com estes Termos de Uso e com nossa Política de Privacidade.</p>
    </div>
  </div>
</div>

app/views/welcome/rental_history.html.erb
<section class="container mt-4 mb-5">
  <div class="row mb-4">
    <div class="col-md-8 mx-auto">
      <div class="d-flex justify-content-between ms-3 mb-2">
        <h3>Equipamentos Alugados</h3>
        <div class="row">
          <% if @pagy.count > 0 %>
            <div class="col-md-12 d-flex justify-content-center">
              <%= pagy_bootstrap_nav(@pagy).html_safe %>
            </div>
          <% end %>
        </div>
      </div>
      <% @order_history.each do |order| %>
        <ul class="list-group">
          <li class="list-group-item">
            <div class="d-flex justify-content-between border border-black rounded p-1">
              <div>
                <div class="d-flex justify-content-between">
                  <p class="me-4 mb-3">Pedido: <%= order.order_code %></p>
                  <p class="mb-3"><%= link_to order.equipament.name, details_equipament_path(id: order.equipament_id) %> </p>
                </div>
                <div class="d-flex">
                  <p class="me-5 mb-0">Início: <%= order.period_start.strftime('%d/%m/%Y') %></p>
                  <p>Fim: <%= order.period_end.strftime('%d/%m/%Y') %> </p>
                </div>
              </div>
              <div class="text-end">
                <p>Custo: <%= number_to_currency(order.tot_rent_value, unit: "R$ ", separator: ",", delimiter: ".")%></p>
                <p>Status: <%= order.status %> </p>
              </div>
            </div>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</section>

app/views/welcome/sobre.html.erb
<!-- Seção de Informações -->
<section class="container py-5">
  <div class="row">
    <div class="col-md-6">
      <h2>Sobre a EquipoRent</h2>
      <p>Bem-vindo à <strong>EquipoRent</strong>, sua fonte confiável para aluguel de equipamentos por mais de duas
        décadas. Desde o
        nosso início modesto há mais de 20 anos, nos estabelecemos como líderes no mercado, oferecendo uma ampla gama
        de equipamentos, desde os mais simples até os mais sofisticados, a preços competitivos.</p>
      <p>Na <strong>EquipoRent</strong>, entendemos que cada projeto é único e requer soluções personalizadas. É por
        isso que nos
        dedicamos a oferecer uma experiência de aluguel simples e sem complicações, adaptada às necessidades
        individuais de cada cliente. Nossa equipe experiente está sempre pronta para orientá-lo na escolha dos
        melhores equipamentos para o seu projeto, garantindo eficiência e sucesso em cada empreendimento.</p>
      <p>No <strong>EquipoRent</strong>, acreditamos que o sucesso de nossos clientes é o nosso sucesso. Estamos
        comprometidos em fornecer soluções de aluguel de equipamentos que ajudem a impulsionar seus projetos para
        frente, independentemente da sua complexidade ou escala.</p>
      <p>Explore nosso site para descobrir mais sobre nossa ampla gama de serviços e entre em contato conosco hoje
        mesmo para saber como podemos ajudá-lo a atingir seus objetivos de forma eficaz e econômica.</p>
      <p>Obrigado por escolher a <strong>EquipoRent</strong>. Estamos ansiosos para trabalhar com você!</p>
    </div>
    <div class="col-md-6">
      <img src="https://via.placeholder.com/500" alt="Sobre Nós" class="img-fluid">
    </div>
  </div>
</section>