config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, path: '', path_names: { sign_in: 'login', sign_out: 'logout',
      sign_up: 'register' }, controllers: { registrations: 'customers/registrations' }

  namespace :admin do

    devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
    root to: 'dashboard#index', as: 'dashboard'

    resources :customers do
      collection do
        get :search
      end
      member do
        delete :destroy_cover_image
      end
    end

    resources :equipaments do
      collection do
        get :search
      end
      member do
        delete :destroy_avatar_image
      end
    end

    resources :maintenances

    resources :orders do
      collection do
        get :put_fineshed_order
        get :put_canceled_order
        get :put_paid_order
      end
      member do
        get :cancel_order
        get :payment_order
        get :finished_order
        delete :destroy_category_image
      end
    end
  end

  get "sobre", to: "welcome#sobre"
  get "privacidade_termos", to: "welcome#privacidade_termos"
  get "list_equipament", to: "welcome#list_equipament"
  get 'welcome/details_equipament/:id', to: 'welcome#details_equipament', as: 'details_equipament'
  get 'welcome/rental_history', to: 'welcome#rental_history', as: 'my_rental_history'

  resources :rentals, only: [:new, :create, :show]

  resources :contacts, only: [:new, :create]

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
end

app/controllers/rentals_controller.rb
# frozen_string_literal: true

class RentalsController < ApplicationController

  before_action :authenticate_customer!
  before_action :load_order, only: %i[show]

  def show; end

  def new
    @equipament = Equipament.find(params[:id])
    @order = Order.new
    @min_date = Date.today + 1
  end

  def create
    @order = Order.new(order_params)
    @order.assign_attributes(credit_card_name: params[:order][:credit_card_name],
                            credit_card_number: params[:order][:credit_card_number],
                            credit_card_expiry_month: params[:order][:credit_card_expiry_month],
                            credit_card_expiry_year: params[:order][:credit_card_expiry_year],
                            credit_card_security_code: params[:order][:credit_card_security_code])

    if @order.valid?
      @order.save
      equipament = Equipament.find(order_params[:equipament_id])
      equipament.unavailable!
      OrderMailer.send_order_receipt(@order.id).deliver_later
      redirect_to rental_path(@order), notice: "Seu pedido foi concluido com sucesso!!"
    else
      @equipament = Equipament.find(order_params[:equipament_id])
      @min_date = (Date.today + 1) ## .strftime("%d/%m/%Y")
      flash.now[:alert] = @order.errors.full_messages.to_sentence
      render(:new, status: :unprocessable_entity)
    end
  end

  def load_payment_form
    @order = Order.new
    @payment = Payment.new
    respond_to do |format|
      format.turbo_stream { render partial: "payment_form" }
    end
  end

  def update
    if @order.update(order_params)
      redirect_to(admin_order_path(@order), notice: "Pedido atualizado com sucesso !!!")
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  def destroy
    @order.destroy!
  end

  private

  def load_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(
      :customer_id,
      :equipament_id,
      :order_code,
      :period_start,
      :period_end,
      :status,
      :rent_value,
      :tot_rent_value,
      :payment_method,
      :installments,
      :pix_code,
      :ticket_barcode
    )
  end
end

app/views/rentals/_form.html.erb
<section class="container mt-4 mb-4">
  <div class="row justify-content-center">
    <div class="col-md-8 mb-4">
      <div class="card mb-3">
        <div class="card-header bg-primary text-white text-center">
          <h4>Alugar Equipamento</h4>
        </div>
        <div class="card-body" data-controller="rental">
          <%= simple_form_for @order, url: rentals_path, html: { class: 'form-horizontal' } do |f| %>
            <!-- Campos de Periodo e Calculo do aluguel  -->
            <%= f.input :customer_id, as: :hidden, input_html: { value: current_customer.id } %>
            <%= f.input :equipament_id, as: :hidden, input_html: { value: @equipament.id } %>
            <%= f.input :rent_value, as: :hidden, input_html: { value: @equipament.rent_value, "data-rental-target": "rentValue" } %>
            <div class="row mb-3">
              <div class="col-md-6">
                <label for="customer_name" class="form-label">Customer Name:</label>
                <div class="form-control-plaintext">
                  <%= current_customer.name %>
                </div>
              </div>
              <div class="col-md-6">
                <label for="equipament_name" class="form-label">Equipament Name:</label>
                <div class="form-control-plaintext">
                  <%= @equipament.name %>
                </div>
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-6">
                <%= f.input :period_start, as: :date, html5: true, input_html: { class: 'form-control', min: @min_date,
                    required: true, "data-rental-target": "startDate", "data-action": "change->rental#calculateTotal" } %>
              </div>
              <div class="col-md-6">
                <%= f.input :period_end, as: :date, html5: true, input_html: { class: 'form-control', min: Date.today.strftime('%d-%m-%Y'),
                    required: true, "data-rental-target": "endDate", "data-action": "change->rental#calculateTotal rental#showPaymentOptions" } %>
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-6">
                <%= label_tag :formated_rent_value, 'Diária', class: 'form-label' %>
                <%= text_field_tag :formated_rent_value, number_to_currency(@equipament.rent_value, unit: "R$ ", separator: ",", delimiter: "."), class: 'form-control', readonly: true, required: true %>
              </div>
              <div class="col-md-6">
                <%= f.input :tot_rent_value_display, as: :string, input_html: { class: 'form-control', readonly: true, "data-rental-target": "totalValueDisplay" } %>
                <%= f.hidden_field :tot_rent_value, "data-rental-target": "totalValue" %>
              </div>
            </div>
            <!-- Campos de Pagamento -->
            <!-- Campos de Pagamento -->
            <div class="card-body" data-controller="payment" data-action="rental:totalCalculated@window->payment#totalCalculated">
              <%= hidden_field_tag :tot_rent_value, @order.tot_rent_value %>
              <%= hidden_field_tag :order_id, @order.id %>
              <div class="row mb-3 d-none" data-rental-target="paymentOptions">
                <div class="col-md-12">
                  <label for="payment_method" class="form-label">Método de Pagamento:</label>
                  <div class="form-check">
                    <%= f.radio_button :payment_method, 'cartao', class: 'form-check-input', checked: (@order.payment_method == 'cartao'), data: { action: "payment#togglePaymentFields" } %>
                    <%= f.label :payment_method_cartao, 'Cartão de Crédito', class: 'form-check-label' %>
                  </div>
                  <div class="form-check">
                    <%= f.radio_button :payment_method, 'pix', class: 'form-check-input', data: { action: "payment#togglePaymentFields" } %>
                    <%= f.label :payment_method_pix, 'PIX', class: 'form-check-label' %>
                  </div>
                  <div class="form-check">
                    <%= f.radio_button :payment_method, 'boleto', class: 'form-check-input', data: { action: "payment#togglePaymentFields" } %>
                    <%= f.label :payment_method_boleto, 'Boleto', class: 'form-check-label' %>
                  </div>
                </div>
              </div>
              <hr>
              <div id="credit-card-fields" class="d-none" data-payment-target="creditCardFields">
                <div class="row mb-3">
                  <div class="col-md-6">
                    <%= f.input :credit_card_name, label: 'Nome no Cartão', input_html: { class: 'form-control' } %>
                  </div>
                  <div class="col-md-6">
                    <%= f.input :credit_card_number, label: 'Número do Cartão', input_html: { class: 'form-control' } %>
                  </div>
                </div>
                <div class="row mb-3">
                  <div class="col-md-4">
                    <%= f.input :credit_card_expiry_month, collection: 1..12, label: 'Mês de Validade', input_html: { class: 'form-control' } %>
                  </div>
                  <div class="col-md-4">
                    <%= f.input :credit_card_expiry_year, collection: Time.now.year..(Time.now.year + 10), label: 'Ano de Validade', input_html: { class: 'form-control' } %>
                  </div>
                  <div class="col-md-4">
                    <%= f.input :credit_card_security_code, label: 'Código de Segurança', input_html: { class: 'form-control' } %>
                  </div>
                </div>
                <div class="row mb-3">
                  <div class="col-md-12">
                    <%= f.input :installments, label: 'Parcelas', collection: [], input_html: { class: 'form-control', 'data-payment-target': 'installments' } %>
                  </div>
                </div>
              </div>
              <div id="pix-fields" class="d-none" data-payment-target="pixFields">
                <div class="row mb-3">
                  <div class="col-md-6">
                    <%= f.input :total_rent_value, as: :string, input_html: { class: 'form-control', readonly: true, "data-payment-target": "pixTotalValue" } %>
                  </div>
                  <div class="col-md-6">
                    <%= f.input :pix_code, label: 'Código PIX', input_html: { class: 'form-control', readonly: true, value: '123456789012345' } %>
                  </div>
                </div>
              </div>
              <div id="boleto-fields" class="d-none" data-payment-target="boletoFields">
                <div class="row mb-3">
                  <div class="col-md-5">
                    <%= f.input :total_rent_value, as: :string, input_html: { class: 'form-control', readonly: true, "data-payment-target": "boletoTotalValue" } %>
                  </div>
                  <div class="col-md-7">
                    <%= f.input :ticket_barcode, label: 'Código de Barras do Boleto', input_html: { class: 'form-control', readonly: true, value: '12345678901234567890123456789012345678901234' } %>
                  </div>
                </div>
              </div>
            </div>
            <div class="card-footer d-flex justify-content-between">
              <%= link_to 'Cancelar', list_equipament_path, class: 'btn btn-secondary' %>
              <%= f.button :submit, "Confirmar", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/rentals/_payment_form.html.erb
<section class="container">
  <div class="row justify-content-center">
    <% flash.each do |key, value| %>
      <div data-controller="flash-message" data-action="click->flash-message#removeMessage" id="flash-message" class="flash <%= key %> alert alert-success bold text-black" data-flash-message-target="message"><%= value %></div>
    <% end %>
    <div class="col-md-10">
      <div class="card">
        <div class="card-header bg-primary text-white text-center">
          <h4>Pagamento</h4>
        </div>
        <div class="card-body" data-controller="payment">
          <%= simple_form_for payment,  html: { class: 'form-horizontal' } do |f| %>
            <%= hidden_field_tag :tot_rent_value, @order.tot_rent_value %>
            <%= hidden_field_tag :order_id, @order.id %>
            <div class="row mb-3">
              <div class="col-md-12">
                <label for="payment_method" class="form-label">Método de Pagamento:</label>
                <div class="form-check">
                  <%= f.radio_button :payment_method, 'cartao', class: 'form-check-input', data: { action: "payment#togglePaymentFields" } %>
                  <%= f.label :payment_method_cartao, 'Cartão de Crédito', class: 'form-check-label' %>
                </div>
                <div class="form-check">
                  <%= f.radio_button :payment_method, 'pix', class: 'form-check-input', data: { action: "payment#togglePaymentFields" } %>
                  <%= f.label :payment_method_pix, 'PIX', class: 'form-check-label' %>
                </div>
                <div class="form-check">
                  <%= f.radio_button :payment_method, 'boleto', class: 'form-check-input', data: { action: "payment#togglePaymentFields" } %>
                  <%= f.label :payment_method_boleto, 'Boleto', class: 'form-check-label' %>
                </div>
              </div>
            </div>
            <hr>
            <div id="credit-card-fields" class="d-none" data-payment-target="creditCardFields">
              <div class="row mb-3">
                <div class="col-md-6">
                  <%= f.input :card_number, label: 'Número do Cartão', input_html: { class: 'form-control', placeholder: '0000 0000 0000 0000' } %>
                </div>
                <div class="col-md-3">
                  <%= f.input :expiry_date, label: 'Data de Validade', input_html: { class: 'form-control', placeholder: 'MM/AA' } %>
                </div>
                <div class="col-md-3">
                  <%= f.input :cvv, label: 'CVV', input_html: { class: 'form-control', placeholder: '000' } %>
                </div>
              </div>
              <div class="row mb-3">
                <div class="col-md-6">
                  <%= f.input :card_holder_name, label: 'Nome no Cartão', input_html: { class: 'form-control', placeholder: 'Nome completo' } %>
                </div>
                <div class="col-md-6">
                  <%= f.input :cpf, label: 'CPF', input_html: { class: 'form-control', placeholder: '000.000.000-00' } %>
                </div>
              </div>
            </div>
            <div id="pix-fields" class="d-none" data-payment-target="pixFields">
              <div class="row mb-3">
                <div class="col-md-12">
                  <%= f.input :pix_key, label: 'Chave PIX', input_html: { class: 'form-control', placeholder: 'Digite a chave PIX' } %>
                </div>
              </div>
            </div>
            <div id="boleto-fields" class="d-none" data-payment-target="boletoFields">
              <div class="row mb-3">
                <div class="col-md-6">
                  <%= f.input :boleto_name, label: 'Nome', input_html: { class: 'form-control', placeholder: 'Nome completo' } %>
                </div>
                <div class="col-md-6">
                  <%= f.input :boleto_cpf, label: 'CPF', input_html: { class: 'form-control', placeholder: '000.000.000-00' } %>
                </div>
                <div class="col-md-12">
                  <%= f.input :boleto_email, label: 'E-mail', input_html: { class: 'form-control', placeholder: 'email@example.com' } %>
                </div>
                <div class="col-md-6">
                  <%= f.input :boleto_address, label: 'Endereço', input_html: { class: 'form-control', placeholder: 'Rua, número, bairro' } %>
                </div>
                <div class="col-md-3">
                  <%= f.input :boleto_city, label: 'Cidade', input_html: { class: 'form-control', placeholder: 'Cidade' } %>
                </div>
                <div class="col-md-3">
                  <%= f.input :boleto_zipcode, label: 'CEP', input_html: { class: 'form-control', placeholder: '00000-000' } %>
                </div>
              </div>
            </div>
            <div class="card-footer d-flex justify-content-between">
              <%= link_to 'Cancelar', list_equipament_path, class: 'btn btn-secondary' %>
              <%= f.button :submit, "Confirmar Pagamento", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/rentals/_rental.html.erb
<section class="container mt-3" id="<%= dom_id order %>">
  <div class="row justify-content-center">
    <% flash.each do |key, value| %>
      <div data-controller="flash-message" data-action="click->flash-message#removeMessage" id="flash-message" class="flash <%= key %> alert alert-success bold text-black" data-flash-message-target="message"><%= value %></div>
    <% end %>
    <div class="col-md-8">
      <div class="card">
        <div class="card-header bg-primary text-white text-center">
          <h4>Detalhes do Aluguel</h4>
        </div>
        <div class="card-body">
          <h5>Detalhes da Ordem</h5>
          <div class="row mb-3">
            <div class="col-md-6">
              <p><strong>Código da Ordem:</strong> <%= order&.order_code %></p>
            </div>
            <div class="col-md-6">
              <p><strong>Data de Início:</strong> <%= order&.period_start.strftime("%d/%m/%Y") %></p>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-md-6">
              <p><strong>Data de Término:</strong> <%= order&.period_end.strftime("%d/%m/%Y") %></p>
            </div>
            <div class="col-md-6">
              <p><strong>Valor Total do Aluguel:</strong> <%= number_to_currency(order&.tot_rent_value, unit: "R$ ", separator: ",", delimiter: ".") %></p>
            </div>
          </div>
          <h5>Detalhes do Pagamento</h5>
          <div class="row mb-3">
            <div class="col-md-6">
              <p><strong>Método de Pagamento:</strong> <%= order&.payment_method.capitalize %></p>
            </div>
            <div class="col-md-6">
              <p><strong>Valor pago:</strong> <%= number_to_currency(order&.tot_rent_value, unit: "R$ ", separator: ",", delimiter: ".") %></p>
            </div>
          </div>
          <% if order.payment_method == 'cartao' %>
            <div class="row mb-3">
              <div class="col-md-6">
                <p><strong>Numero de parcelas:</strong> <%= order&.installments %></p>
              </div>
              <div class="col-md-6">
                <p><strong>Valor da parcela:</strong> <%= number_to_currency((order&.tot_rent_value / order&.installments) , unit: "R$ ", separator: ",", delimiter: ".") %></p>
              </div>
            </div>
          <% elsif order.payment_method == 'pix' %>
            <div class="row mb-3">
              <div class="col-md-6">
                <p><strong>Código PIX:</strong> <%= order&.pix_code %></p>
              </div>
            </div>
          <% elsif order.payment_method == 'boleto' %>
            <div class="row mb-3">
              <div class="col-md-6">
                <p><strong>Código de Barras do Boleto:</strong> <%= order&.ticket_barcode %></p>
              </div>
            </div>
          <% end %>
        </div>
        <div class="card-footer d-flex justify-content-between">
          <%= link_to 'Continuar', list_equipament_path(order&.equipament_id), class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/rentals/_toolbar.html.erb
<div class="toolbar py-5 pb-lg-15" id="kt_toolbar" >
  <div id="kt_toolbar_container" class="container-xxl d-flex flex-wrap flex-stack" >
    <div class="page-title d-flex flex-column me-3" >
      <h1 class="d-flex text-black fw-bold my-1 ">Pedidos</h1>
    </div>
    <div class="d-flex align-items-center py-3 py-md-1" >
    </div>
  </div>
</div>

app/views/rentals/index.html.erb
<div class="container-fluid">
  <div class="d-flex align-items-center">
    <h3 class="flex-grow-1">Lista de Pedidos </h3>
    <div class="input-group ms-3" style="width: 550px;">
      <%= form_with url: orders_path, method: :get, local: true, class: "d-flex w-100" do %>
        <%= text_field_tag :search, nil, class: "form-control input-sm", placeholder: "Pesquisar Pedido(s)...", aria_label: "Pesquisar" %>
        <%= button_tag(type: 'submit', class: "btn btn-success me-5 text-black-500 hover:underline", title: "Pesquisar", alt: "pesquisar") do %>
          <%= image_tag "icons/gray/lupa.svg" %>
        <% end %>
      <% end %>
    </div>
    <div class="list-actions">
      <%= link_to "Novo", new_order_path, class:"ms-3 btn btn-primary" %>
    </div>
  </div>
  <section class="">
    <div class="row">
      <div class="col">
        <table class="table table-bordered table-striped">
          <thead class="thead-dark">
            <tr>
              <th class="bg-black text-white" scope="col">Codigo pedido</th>
              <th class="bg-black text-white" scope="col">Cliente</th>
              <th class="bg-black text-white" scope="col">Equipamento</th>
              <th class="bg-black text-white" scope="col">Inicio</th>
              <th class="bg-black text-white" scope="col">Fim</th>
              <th class="bg-black text-white" scope="col">R$ Aluguel</th>
              <th class="bg-black text-white" scope="col">Status</th>
              <th class="bg-black text-white" scope="col">Ações</th>
            </tr>
          </thead>
          <tbody>
            <!-- Exemplo de cliente cadastrado -->
            <% @orders.each do |order| %>
              <tr>
                <td><%= order&.order_code %></td>
                <td><%= order.customer.name %></td>
                <td><%= order.equipament.name %></td>
                <td><%= order&.period_start.strftime('%d/%m/%Y') %></td>
                <td><%= order&.period_end.strftime('%d/%m/%Y') %></td>
                <td><%= number_to_currency(order.tot_rent_value, unit: "R$ ", separator: ",", delimiter: ".") %></td>
                <td><%= order.status %></td>
                <td class="d-flex justify-content-between">
                  <%= link_to edit_order_path(order), title: "Edit", alt: "edit"  do %>
                    <%= image_tag "icons/gray/edit.svg" %>
                  <% end %>
                  <%= link_to order, method: :delete, data: {
                        turbo_method: :delete, turbo_confirm: 'Are you sure?' }, 
                        class: "text-red-500 hover:underline", title: "Delete", alt: "delete"   do  %>
                    <%= image_tag "icons/gray/close.svg" %>
                  <% end %>
                </td>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </section>
  </div>

app/views/rentals/load_payment_form.turbo_stream.erb
<turbo-stream action="replace" target="paymentFormContainer">
  <template>
    <%= render partial: 'payment_form', locals: { payment: @payment } %>
  </template>
</turbo-stream>

app/views/rentals/show.html.erb
<%= render 'rental', order: @order  %>